spring.application.name=ecocycle
spring.datasource.url=jdbc:mysql://localhost:3306/ECOCYCLEQAS
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true